name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.3.95.155.107 }}
        username: ${{ secrets.ubuntu }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo -i
          cd ~/my-node-app
          git pull origin main
          npm install
          pm2 restart my-node-app
